### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ucelme** [yakovlevvl/SoundPlayer#2]
2020-01-29 12:36:55.053878+0300 MusicPlayer[47819:6329306] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000009c8620> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-01-29 12:36:55.791048+0300 MusicPlayer[47819:6329306] *** Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'id' does not exist on object 'SongDownload''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   Realm                               0x000000010ebb5b93 +[RLMObjectSchema schemaForObjectClass:] + 4371
	3   Realm                               0x000000010ecbdc3e _ZL16RLMRegisterClassP10objc_class + 302
	4   Realm                               0x000000010ecbec6d __25+[RLMSchema sharedSchema]_block_invoke + 77
	5   CoreFoundation                      0x00007fff23cf9c77 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	6   CoreFoundation                      0x00007fff23cd2e0e -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 238
	7   Realm                               0x000000010ecbe9af +[RLMSchema sharedSchema] + 479
	8   Realm                               0x000000010ec8adfa +[RLMRealm realmWithConfiguration:error:] + 2794
	9   RealmSwift                          0x00000001101301a1 $sSo8RLMRealmC13configurationABSo0A13ConfigurationC_tKcfCTO + 145
	10  RealmSwift                          0x0000000110130059 $s10RealmSwift0A0CACyKcfC + 105
	11  MusicPlayer                         0x000000010e344a0c $s11MusicPlayer7LibraryC14playlistsCountSivg + 60
	12  MusicPlayer                         0x000000010e325be4 $s11MusicPlayer11PlaylistsVCC14collectionView_22numberOfItemsInSectionSiSo012UICollectionF0C_SitF + 164
	13  MusicPlayer                         0x000000010e325dcc $s11MusicPlayer11PlaylistsVCC14collectionView_22numberOfItemsInSectionSiSo012UICollectionF0C_SitFTo + 76
	14  UIKitCore                           0x00007fff478a9a57 -[UICollectionViewData _updateItemCounts] + 656
	15  UIKitCore                           0x00007fff478ac7e1 -[UICollectionViewData numberOfSections] + 22
	16  UIKitCore                           0x00007fff478b73ab -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:] + 503
	17  UIKitCore                           0x00007fff478b95ab -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] + 231
	18  UIKitCore                           0x00007fff478b1d75 -[UICollectionViewFlowLayout prepareLayout] + 246
	19  UIKitCore                           0x00007fff478a9f0d -[UICollectionViewData _prepareToLoadData] + 220
	20  UIKitCore                           0x00007fff478aaa16 -[UICollectionViewData validateLayoutInRect:] + 53
	21  UIKitCore                           0x00007fff47875282 -[UICollectionView layoutSubviews] + 240
	22  UIKitCore                           0x00007fff485784bd -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
	23  QuartzCore                          0x00007fff2b131db1 -[CALayer layoutSublayers] + 255
	24  QuartzCore                          0x00007fff2b137fa3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 517
	25  QuartzCore                          0x00007fff2b1438da _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 80
	26  QuartzCore                          0x00007fff2b08a848 _ZN2CA7Context18commit_transactionEPNS_11TransactionEd + 324
	27  QuartzCore                          0x00007fff2b0bfb51 _ZN2CA11Transaction6commitEv + 643
	28  UIKitCore                           0x00007fff480aa575 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 81
	29  CoreFoundation                      0x00007fff23bd429c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	30  CoreFoundation                      0x00007fff23bd3a08 __CFRunLoopDoBlocks + 312
	31  CoreFoundation                      0x00007fff23bce894 __CFRunLoopRun + 1284
	32  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	33  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	34  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	35  MusicPlayer                         0x000000010e3ee7cb main + 75
	36  libdyld.dylib                       0x00007fff5227ec25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by yakovlevvl** [comment]
Fixed in 1.0.1 release.
